# Generated by Django 4.1 on 2022-09-18 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpostcandidate',
            old_name='appointment',
            new_name='interview_appointment',
        ),
    ]
