# Generated by Django 4.1 on 2022-09-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_appointment_jobpostcandidate_interview_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpostcandidate',
            name='interview_appointment',
        ),
        migrations.AddField(
            model_name='jobpostcandidate',
            name='interview_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobpostcandidate',
            name='interview_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
