# Generated by Django 4.1 on 2022-09-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_jobpostcandidate_interview_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpostcandidate',
            name='interview_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobpostcandidate',
            name='interview_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
