# Generated by Django 4.1 on 2022-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_jobpostcandidate_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostcandidate',
            name='notes',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
