# Generated by Django 4.1 on 2022-09-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobpostcandidate_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostcandidate',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
