# Generated by Django 4.1 on 2022-09-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobpostcandidate_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='accept_candidated',
            field=models.BooleanField(default=True),
        ),
    ]
