# Generated by Django 4.1 on 2022-09-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobpost_accept_candidated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobpost',
            old_name='accept_candidated',
            new_name='accept_candidates',
        ),
    ]
