# Generated by Django 4.1 on 2022-09-19 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_accept_candidated_jobpost_accept_candidates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='accept_candidates',
        ),
    ]
